### ISSUE TITLE
Flipper Zero App resets favorites when synced

### ISSUE THREAD

**Issue by alex1001458** [Flipper-Zero/Flipper-Android-App#521]
### Describe the bug.

Every application or file in your favorites tab the flipper zero app doesn't recognize in it's archive menu (eg. any app inside a folder) will get removed from the favorites tab when you sync it with the flipper zero.

### Reproduction

1. "Pin" something through the quick menu (press down on screen saver) the Flipper app doesn't recognize, such as an IR remote you have in a folder.
2. Turn on Flipper app and let it synchronize (you may have to press "synchronize" yourself)
3. Watch your favorited item disappear.

**Comment by skotopes** [comment]
@LionZXY looks like this one is for you

**Comment by LionZXY** [comment]
@alex1001458 What version of the app do you have? Does it reproduce on the latest dev?

**Comment by blackvault88** [comment]
fyi, the same happens with key files (eg subghz, rfid, IR, ...) that are not in their root app folder, but in subfolders (eg an rfid key in /ext/lfrfid/somefolder instead of in /ext/lfrfid)
you can pin them in the flipper zero, but after syncing with the android app, it does not show up in favorites in the android app and it gets removed from the favorites list in the flipper zero...

**Comment by LionZXY** [comment]
> the keys in subfolders are not synced to mobile app, they do not show up at all

It's okay now. We'll improve it in the future (you can subscribe to #284 )
